version: 2
jobs:
  test:
    working_directory: ~/server
    docker:
      - image: circleci/node:4.8.2
      - image: node:12
    steps:
      - checkout
      - run:
          name: Install yarn dependencies & test backend
          command: yarn install --ignore-engines && yarn test:ci
          path: server
      - store_test_results:
          path: server/test-results
      - store_artifacts:
          path: test-results

workflows:
  version: 2
  build_and_test:
    jobs:
      - test