

version: 2
jobs:
  build:
    docker:
      - image: circleci/node:10
      - image: circleci/postgres:9.6.2-alpine
        environment:
          POSTGRES_USER: testuser
          POSTGRES_DB: spacehoptest

    steps:
      - checkout
      - run:
          name: Install .env 
          command: echo "NODE_ENV=test" >> .env
          path: server
      - run:
          name: Install yarn dependencies(backend)
          command: yarn install --ignore-engines
          path: server
      - run:
          name: Test backend
          command: yarn run test:ci
          path: server
      - store_test_results:
          path: server/test-results
      - store_artifacts:
          path: test-results

      - run:
          name: Install yarn dependencies(frontend)
          command: yarn install --ignore-engines
          path: client
      - run:
          name: Test frontend
          command: yarn run test:ci
          path: client
          environment:
            JEST_JUNIT_OUTPUT_DIR: ./test-results/
      - store_test_results:
          path: client/test-results
      - store_artifacts:
          path: client/test-results
