version: 2
jobs:
  build:
    working_directory: ~/server
    docker:
      - image: circleci/node:4.8.2
    steps:
      - checkout
      - restore_cache:
          key: dependency-cache-{{ checksum "package.json" }}
          path: server
      - run:
          name: Install yarn dependencies
          command: yarn install
          path: server
      - save_cache:
          key: dependency-cache-{{ checksum "package.json" }}
          paths:
            - server/node_modules
  test:
    docker:
      - image: circleci/node:4.8.2
    steps:
      - checkout
      - run:
          name: Test
          command: yarn run test
          path: server

workflows:
  version: 2
  build_and_test:
    jobs:
      - build
      - test:
          requires:
            - build
          filters:
            branches:
              only: develop