version: 2
jobs:
  build:
    docker:
      - image: circleci/node:10
      - image: circleci/postgres:9.6.2-alpine
    steps:
      - checkout
      - run:
          name: install postgres
          command: apt-get install -y postgresql-client
          path: server
      - run:
          name: create user of postgres
          command: psql -c "create role testuser login password '1234';" -U postgres
          path: server
      - run:
          name: create database for test
          command: psql -c 'create database spacehoptest;' -U postgres
          path: server
      - run:
          name: Install yarn dependencies
          command: yarn install --ignore-engines
          path: server
      - run:
          name: Test backend
          command: yarn run test:ci
          path: server
      - store_test_results:
          path: server/test-results
      - store_artifacts:
          path: test-results