version: 2
jobs:
  build:
    working_directory: ~/server
    docker:
      - image: circleci/node:4.8.2
      - image: node:12
    steps:
      - checkout
      - run:
          name: Install yarn dependencies
          command: yarn install --ignore-engines
      - run:
          name: Test backend
          command: mkdir -p test-results && mocha test --reporter mocha-junit-reporter --reporter-options mochaFile=./test-results/file.xml
      - store_test_results:
          path: server/test-results
      - store_artifacts:
          path: test-results
